### ISSUE TITLE
hooks4git --init throws: "I am afraid I can't to that. Looks like your .git folder is not standard"

### ISSUE THREAD

**Issue by edouard-lopez** [lovato/hooks4git#43]
Running the `hooks4git --init` on an existing repo a team-mate got the following error:

    I am afraid I can't to that. Looks like your .git folder is not standard.

**Comment by edouard-lopez** [comment]
After a quick look into it, the `.git/hooks/` directory was missing.

### Solution

    cd your-repo/
    mkdir -p .git/hooks/
    hooks4git --init

Hooks4git should check support this scenario

**Comment by lovato** [comment]
@edouard-lopez you are absolutely right.

**Comment by lovato** [comment]
Here is the working version in DEV

![image](https://user-images.githubusercontent.com/1213774/56364103-2a240a00-61c4-11e9-9d3a-4e1341ff80a6.png)

**Comment by lovato** [comment]
@edouard-lopez Please, add comments here or on #45 
Ideally, I wish to release it immediately.

**Comment by edouard-lopez** [comment]
Do we need to run it twice?

**Comment by lovato** [comment]
Oh no, this was my test BEFORE and AFTER the fix.

**Comment by lovato** [comment]
I can assemble a dev version if you want to test it before an official release. Or I can just send it to production. I did my tests here and it seems ok.

**Comment by lovato** [comment]
I proceeded with default steps, sending it here: https://test.pypi.org/project/hooks4git
After a few more testing, I will upgrade it to prod. You can install it from testpypi normally, and later upgrade it with production version w/o any issue. It is just a normal release, except it is stored on a spare server.

**Comment by lovato** [comment]
@edouard-lopez Would you like to test it first? Or else, I can just send it to production.

**Comment by lovato** [comment]
@edouard-lopez Please take a look at https://github.com/lovato/hooks4git/pull/46 ... PR45 was merged to develop hours before your comment.
