### ISSUE TITLE
Subcommand fail

### ISSUE THREAD

**Issue by edouard-lopez** [lovato/hooks4git#57]
I have the following config

```
[scripts]
format_and_version = git add -- "$(yarn --silent format)"

[hooks.pre-commit.scripts]
format = format_and_version

[hooks.pre-push.scripts]
```

But when I run `git commit` I got:

```
STEP | $ git add -- "$(yarn --silent format)"
SERR | fatal: pathspec '"$(yarn' did not match any files
FAIL | 'format/format_and_version' step failed to execute
```

Removing quotes gives the same result.

**Comment by lovato** [comment]
Will investigate that.

**Comment by lovato** [comment]
Reproduced with:
```
  STEP | $ git add -- "$(echo 1)"
  SERR | fatal: pathspec '"$(echo' did not match any files
  FAIL | 'format_and_version/format_and_version' step failed to execute
```

**Comment by lovato** [comment]
Looks like it is fixed. 0.4.x is being coded, with this fix. It's a major rework, partially done, but stable as of today, with lots of tests added. Will look for or patch current production version, or release this one ASAP.

**Comment by lovato** [comment]
You can try with this earlier build. I had to do a rework on os call too, so ... seems to be working so far.
https://test.pypi.org/project/hooks4git/

**Comment by edouard-lopez** [comment]
Works fine, thanks
