### ISSUE TITLE
hooks4git --init does not detect .git folder

### ISSUE THREAD

**Issue by venugov** [lovato/hooks4git#64]
I am running hooks4git --init command on Windows 10 git bash and it does not detect .git folder even though the folder is present.(version - 0.4.271)
![image](https://user-images.githubusercontent.com/49195832/78096396-0e2a7000-73f7-11ea-8b97-4f167c1bf949.png)

**Comment by lovato** [comment]
There was a bug on the last version in which GitBash was trying to run /bin/bash to execute the syscall. It should work, but it actually does not.
https://github.com/lovato/hooks4git/pull/65
